### PR TITLE
Fix logic for driver URL calculation

### LINKED ISSUE #64: Unable to download installer for nvidia driver 460.32.03
Trying to install the latest nvidia driver (460.32.03) in the support list:
```
gsutil ls -l gs://nvidia-drivers-us-public/tesla/460.32.03/
 178089544  2021-01-20T10:33:42Z  gs://nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03.run
      1298  2021-01-20T10:33:49Z  gs://nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03.run.gcmanifest
        99  2021-01-20T10:33:07Z  gs://nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03.run.sha256
TOTAL: 3 objects, 178090941 bytes (169.84 MiB)
```
But failed:
```
+ COS_KERNEL_INFO_FILENAME=kernel_info
+ COS_KERNEL_SRC_HEADER=kernel-headers.tgz
+ TOOLCHAIN_URL_FILENAME=toolchain_url
+ TOOLCHAIN_ENV_FILENAME=toolchain_env
+ TOOLCHAIN_PKG_DIR=/build/cos-tools
+ CHROMIUMOS_SDK_GCS=https://storage.googleapis.com/chromiumos-sdk
+ ROOT_OS_RELEASE=/root/etc/os-release
+ KERNEL_SRC_HEADER=/build/usr/src/linux
+ NVIDIA_DRIVER_VERSION=460.32.03
+ NVIDIA_DRIVER_MD5SUM=
+ NVIDIA_INSTALL_DIR_HOST=/home/kubernetes/bin/nvidia
+ NVIDIA_INSTALL_DIR_CONTAINER=/usr/local/nvidia
+ ROOT_MOUNT_DIR=/root
+ CACHE_FILE=/usr/local/nvidia/.cache
+ LOCK_FILE=/root/tmp/cos_gpu_installer_lock
+ LOCK_FILE_FD=20
+ set +x
[INFO    2021-02-03 22:32:25 UTC] PRELOAD: false
[INFO    2021-02-03 22:32:25 UTC] Running on COS build id 12371.1088.0
[INFO    2021-02-03 22:32:25 UTC] Data dependencies (e.g. kernel source) will be fetched from https://storage.googleapis.com/cos-tools/12371.1088.0
[INFO    2021-02-03 22:32:25 UTC] Checking if this is the only cos-gpu-installer that is running.
[INFO    2021-02-03 22:32:25 UTC] Checking if third party kernel modules can be installed
/tmp/esp /
/
[INFO    2021-02-03 22:32:25 UTC] Checking cached version
[INFO    2021-02-03 22:32:25 UTC] Cache file /usr/local/nvidia/.cache not found.
[INFO    2021-02-03 22:32:25 UTC] Did not find cached version, building the drivers...
/usr/local/nvidia /
[INFO    2021-02-03 22:32:25 UTC] Downloading GPU installer ... 
[INFO    2021-02-03 22:32:26 UTC] Downloading from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03-diagnostic.run
[INFO    2021-02-03 22:32:26 UTC] Downloading GPU installer from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03-diagnostic.run
curl: (22) The requested URL returned error: 404 

real	0m0.121s
user	0m0.013s
sys	0m0.003s
[WARNING 2021-02-03 22:32:26 UTC] Error fetching GPU installer from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03-diagnostic.run, retrying
curl: (22) The requested URL returned error: 404 

real	0m0.086s
user	0m0.011s
sys	0m0.005s
[WARNING 2021-02-03 22:32:27 UTC] Error fetching GPU installer from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03-diagnostic.run, retrying
curl: (22) The requested URL returned error: 404 

real	0m0.080s
user	0m0.010s
sys	0m0.006s
[WARNING 2021-02-03 22:32:28 UTC] Error fetching GPU installer from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03-diagnostic.run, retrying
curl: (22) The requested URL returned error: 404 

real	0m0.092s
user	0m0.013s
sys	0m0.003s
[WARNING 2021-02-03 22:32:29 UTC] Error fetching GPU installer from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03-diagnostic.run, retrying
curl: (22) The requested URL returned error: 404 

real	0m0.090s
user	0m0.014s
sys	0m0.002s
[ERROR   2021-02-03 22:32:30 UTC] Could not download GPU installer from https://storage.googleapis.com/nvidia-drivers-us-public/tesla/460.32.03/NVIDIA-Linux-x86_64-460.32.03-diagnostic.run, giving up.
```

I found a bug in the code:
https://github.com/GoogleCloudPlatform/cos-gpu-installer/blob/c9b2ae4d4cec9b6c0fe7a955fff38c2b806a94ba/cos-gpu-installer-docker/gpu_installer_url_lib.sh#L59
```
  if (( "${major_version}" < 390 )); then
    # Versions prior to 390 are downloaded from the upstream location.
    echo "https://us.download.nvidia.com/tesla/${driver_version}/NVIDIA-Linux-x86_64-${driver_version}.run"
  elif (( "${major_version}" == 390 )); then
    # The naming format changed after version 390.
    echo "https://storage.googleapis.com/nvidia-drivers-${download_location}-public/TESLA/NVIDIA-Linux-x86_64-${driver_version}.run"
  elif (( "${major_version}" >= 396 )) && (( "${minor_version}" >= 37 )); then
    # Apparently the naming format changed again starting since 396.37.
    echo "https://storage.googleapis.com/nvidia-drivers-${download_location}-public/tesla/${driver_version}/NVIDIA-Linux-x86_64-${driver_version}.run"
  else
    echo "https://storage.googleapis.com/nvidia-drivers-${download_location}-public/tesla/${driver_version}/NVIDIA-Linux-x86_64-${driver_version}-diagnostic.run"
  fi
```
It should be something like: `elif (( "${major_version}" > 396 )) ||  (( "${major_version}" == 396 )) && (( "${minor_version}" >= 37 )); then `

### PR DESCRIPTION
**Pull request by arnav-kansal**
Found all the drivers availble in the google storage buckets using:
`gsutil ls -r gs://nvidia-drivers-us-public/ | grep -E -i -v
'sha256|.gcmanifest|GRID' | grep ".run" | sort | uniq -u`

The driver URL logic method has been retro fitted to retrieve all
versions availble in the storage bucket.

### CODE REVIEW

File: cos-gpu-installer-docker/gpu_installer_url_lib.sh [hunk 1]
```diff
@@ -53,14 +53,14 @@ default_installer_download_url() {
...
     # The naming format changed after version 390.
     echo "https://storage.googleapis.com/nvidia-drivers-${download_location}-public/TESLA/NVIDIA-Linux-x86_64-${driver_version}.run"
-  elif (( "${major_version}" >= 396 )) && (( "${minor_version}" >= 37 )); then
+  elif (( "${major_version}" == 396 )) && (( "${minor_version}" == 26 )); then
     # Apparently the naming format changed again starting since 396.37.
-    echo "https://storage.googleapis.com/nvidia-drivers-${download_location}-public/tesla/${driver_version}/NVIDIA-Linux-x86_64-${driver_version}.run"
-  else
     echo "https://storage.googleapis.com/nvidia-drivers-${download_location}-public/tesla/${driver_version}/NVIDIA-Linux-x86_64-${driver_version}-diagnostic.run"
+  else
+    echo "https://storage.googleapis.com/nvidia-drivers-${download_location}-public/tesla/${driver_version}/NVIDIA-Linux-x86_64-${driver_version}.run"
```
Comment (rkolchmeyer) [inline cos-gpu-installer-docker/gpu_installer_url_lib.sh]: Can you update the comments as well? Also, can you include comments that explain missing version ranges? Something like:

```
if (( "${major_version}" < 390 )); then
  # Versions prior to 390 ...
elif (( "${major_version}" == 390 ... )); then
  # 390.46 is the only 390 version
elif (( "${major_version}" == 396 ... )); then
  # There are no versions between 390.46 and 396.26
else
  # All versions over 396.26
```

Comment (arnav-kansal) [reply cos-gpu-installer-docker/gpu_installer_url_lib.sh]: Updated the comments. There exists one version between 390.46 and 396.26 which is 390.116 but that one conforms to the naming format seen in the later versions.

**Review by rkolchmeyer — APPROVED** [review]
